(define (task a b c)
        (if (> a b) (if (> b c) (+ (* a a) (* b b))
                                (+ (* a a) (* c c))
                    )
                    (if (> a c) (+ (* b b) (* a a))
                                (+ (* b b) (* c c))
                    )
        )
)

(task 1 2 3)
(task 1 1 1)
(task 1 2 2)
(task 1 1 2)